# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-27 00:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='_userprofile_followers_+', to='app01.UserProfile', verbose_name='我的粉丝'),
        ),
    ]
