# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-27 00:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20170727_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='follow_list',
            field=models.ManyToManyField(blank=True, related_name='my_fans', to='app01.UserProfile', verbose_name='我的关注'),
        ),
    ]
